version: '2'

networks:

  matomo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

services:

  nginx:
    container_name: nginx
    build:
      context: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - matomo  
    networks:
      matomo:
        ipv4_address: 172.18.0.10  
    depends_on:
      - matomo    

  mysql:
    container_name: mysql
    restart: always
    build:
      context: mysql/
      args:
        MYSQL_VERSION: $MYSQL_VERSION
    environment:  
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD    
    volumes:
      - ./mysql/data:/var/lib/mysql  
    networks:
      - matomo

  matomo:
    container_name: matomo
    restart: always
    build:
      context: matomo/
      args:
        MATOMO_PHP_VERSION: $MATOMO_PHP_VERSION
    volumes:
      - ./matomo/config:/var/www/html/config  
    networks:
      - matomo
    depends_on:
      - mysql